config/routes.rb
Rails.application.routes.draw do
  root to: 'plants#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post '/mygarden', to: "gardens#create", as: :gardens
  get '/mygarden', to: "gardens#show", as: :garden
  delete '/mygarden', to: "gardens#destroy", as: :garden_plants

  resources :plants, only: [:index, :show, :create]
  resources :recipes, only: [:index, :show]

  get '/developers', to: "api_keys#show", as: :developer
  post '/developers', to: "api_keys#create", as: :developers


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
        get '/plants/find', to: "plants#find_by"
      resources :plants, only: [:index, :show, :create, :update]
      resources :recipes, only: [:index]
      resources :frost_dates, only: [:index]
    end
  end
end

app/models/recipe.rb
class Recipe
  attr_reader :name,
              :image,
              :ingredients,
              :id,
              :servings,
              :tags,
              :url,
              :source,
              :sourceIcon

  def initialize(data)
    @name = data[:label]
    @image = data[:image]
    @ingredients = data[:ingredientLines]
    @id = data[:uri]
    @servings = data[:yield]
    @tags = data[:healthLabels]
    @url = data[:url]
    @source = data[:source]
    @sourceIcon = data[:sourceIcon]
  end

  def self.service
    EdamamService.new
  end

  def self.all(plant)
    service.all(plant)[:hits].map { |data|
      Recipe.new(data[:recipe])
    }
  end

  def self.find(id)
    Recipe.new(service.find(id).first)
  end
end

app/controllers/api/v1/recipes_controller.rb
module Api
  module V1
    class RecipesController < ApiController
      def index
        respond_with Recipe.all(params[:plant])
      end
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all(params[:plant])
  end

  def show
    @recipe = Recipe.find(params[:eid])
  end
end

app/views/recipes/index.html.erb
<div class="container-fluid plant">
  <% @recipes.each do |recipe| %>
    <table class="table">
      <tr class="table table-success">
        <td>
          <h3 class="plant-text"> <%= link_to recipe.name, recipe_path(recipe.name, eid: recipe.id) %> </h3>
          <%= link_to (image_tag recipe.image, class:"plant-image"), recipe_path(recipe.name, eid: recipe.id) %>
        </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container-fluid plant">
  <table class="table">
    <tr class="table table-success">
      <td>
        <h3 class="plant-text"> <%= link_to @recipe.name, "#{@recipe.url}", target: :blank %> </h3>
        <%= link_to (image_tag @recipe.image, class:"plant-image"), "#{@recipe.url}", target: :blank %>
      </td>
    </tr>
    <tr>
      <td class="ingredient col-xs-6">
        recipe from <%= link_to @recipe.source, "#{@recipe.url}" %>
        <%= link_to "make it", "#{@recipe.url}", class:"btn btn-warning btn-xs recipe", target: :blank %>
      </td>
    </tr>
    <tr>
      <td class="plant-text">servings: <%= @recipe.servings %></td>
    </tr>
    <tr>
      <td>
        <h5 class="plant-text">ingredients:</h5>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li class="ingredient"> <%= ingredient %> </li>
          <% end %>
        </ul>
      </td>
    </tr>
  </table>
</div>