config/routes.rb
Rails.application.routes.draw do
  root to: 'plants#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post '/mygarden', to: "gardens#create", as: :gardens
  get '/mygarden', to: "gardens#show", as: :garden
  delete '/mygarden', to: "gardens#destroy", as: :garden_plants

  resources :plants, only: [:index, :show, :create]
  resources :recipes, only: [:index, :show]

  get '/developers', to: "api_keys#show", as: :developer
  post '/developers', to: "api_keys#create", as: :developers


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
        get '/plants/find', to: "plants#find_by"
      resources :plants, only: [:index, :show, :create, :update]
      resources :recipes, only: [:index]
      resources :frost_dates, only: [:index]
    end
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  before_create :reset_attributes

  belongs_to :user, optional: true
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :optimal_sun, presence: true
  validates :optimal_soil, presence: true
  validates :when_to_plant, presence: true
  validates :growing_from_seed, presence: true
  validates :transplanting, presence: true
  validates :spacing, presence: true

  def upload_image_to_cloudinary(image)
    env = Rails.env
    image_name = File.basename(image,File.extname(image))
    options = {
      :folder => "harvest_helper_#{Rails.env}",
      :public_id => image_name
    }
    response = Cloudinary::Uploader.upload(image, options)

    self.update!('image_url' => response['public_id'])
  end

  def reset_attributes
    self.planting_considerations = "n/a" if self.planting_considerations.nil?
    self.feeding = "n/a" if self.feeding.nil?
    self.other_care = "n/a" if self.other_care.nil?
    self.diseases = "n/a" if self.diseases.nil?
    self.harvesting = "n/a" if self.harvesting.nil?
    self.storage_use = "n/a" if self.storage_use.nil?
    self.watering = "n/a" if self.watering.nil?
  end
end

app/controllers/api/v1/plants_controller.rb
module Api
  module V1
    class PlantsController < ApiController
      def index
        respond_with Plant.all
      end

      def find_by
        respond_with Plant.find_by(plant_params)
      end

      def show
        respond_with Plant.find(params[:id])
      end

      def create
        respond_with Plant.create(plant_params)
      end

      def update
        respond_with Plant.find(params[:id]).update(plant_params)
      end

      private
        def plant_params
          params.permit(
            :id,
            :name,
            :description,
            :optimal_sun,
            :optimal_soil,
            :planting_considerations,
            :when_to_plant,
            :growing_from_seed,
            :transplanting,
            :spacing,
            :watering,
            :feeding,
            :other_care,
            :diseases,
            :pests,
            :harvesting,
            :storage_use,
          )
        end
    end
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  respond_to :html, :json

  def index
    term = params[:term].try(:downcase)
    plants = Plant.where("LOWER(name) LIKE ?", "%#{term}%").take(7)
    respond_with(plants)
  end

  def show
    @plant = Plant.find(params["id"])

    location = Location.where(address: params[:zip]).first_or_create if params[:zip]
    frostdate = FrostDate.find(location.latitude, location.longitude) if location
    respond_with(frostdate)
  end

  def create
    plant = Plant.find_by("LOWER(name) LIKE ?", "%#{params[:search]}%")
    if !plant.nil?
      redirect_to plant_path(plant)
    else
      flash.now[:alert] = "Sorry, couldn't find that plant.  Search again."
      render :index
    end
  end
end

app/views/plants/index.html.erb
<div class="container image-back">
  <div class="container centerDiv">
    <h4 class="garden-search ingredient">What do you want to grow?</h4><br>
    <div class="search-bar">
      <%= form_tag(plants_path, method: "post") do %>
        <%= text_field_tag(:search) %>
      <% end %>
      <a id='search-results' class="text-align-center"></a>
    </div>
  </div>
</div>

app/views/plants/show.html.erb
<div class="container-fluid plant">
  <h1 class="plant-text"> <%= @plant.name %> </h1>
  <p class="plant-text"> <%= @plant.description %> </p>
  <%= cl_image_tag(@plant.image_url, :class=>'plant-image', :height=>300, :fetch_format=>:auto, :crop=>"scale") %>
  
  <%= button_to "add to my garden", gardens_path, params: {plant_id: @plant.id}, class: "btn btn-primary button" %><br>
  <table class="table table-bordered">
    <tr>
      <th class="plant-text bold">optimal_sun</th>
      <th class="plant-text bold">optimal_soil</th>
    </tr>
    <tr class="table table-success">
      <td class="plant-text"> <%= @plant.optimal_sun %> </td>
      <td class="plant-text"> <%= @plant.optimal_soil %> </td>
    </tr>
  </table>
  <a name="when_to_plant"></a>
  <h4 class="plant-text bold">planting considerations:</h4>
  <p class="plant-text">
    <%= @plant.planting_considerations %>
  </p>
  <h4 class="plant-text bold">when to plant:</h4>
  <p class="plant-text">
    <%= @plant.when_to_plant %>
  </p>
  <h4 class="plant-text bold">growing from seed:</h4>
  <p class="plant-text">
    <%= @plant.growing_from_seed %>
  </p>
  <h4 class="plant-text bold">transplanting:</h4>
  <p class="plant-text">
    <%= @plant.transplanting %>
  </p>
  <h4 class="plant-text bold">spacing:</h4>
  <p class="plant-text">
    <%= @plant.spacing %>
  </p>
  <a name="care"></a>
  <h4 class="plant-text bold">watering:</h4>
  <p class="plant-text">
    <%= @plant.watering %>
  </p>
  <h4 class="plant-text bold">feeding:</h4>
  <p class="plant-text">
    <%= @plant.feeding %>
  </p>
  <h4 class="plant-text bold">other care:</h4>
  <p class="plant-text">
    <%= @plant.other_care %>
  </p>
  <h4 class="plant-text bold">diseases:</h4>
  <p class="plant-text">
    <%= @plant.diseases %>
  </p>
  <h4 class="plant-text bold">pests:</h4>
  <p class="plant-text">
    <%= @plant.pests %>
  </p>
  <a name="harvesting"></a>
  <h4 class="plant-text bold">harvesting:</h4>
  <p class="plant-text">
    <%= @plant.harvesting %>
  </p>
  <h4 class="plant-text bold">storage and use:</h4>
  <p class="plant-text">
    <%= @plant.storage_use %>
  </p>
  <h4 class="plant-text bold">recipes:</h4>
  <p class="plant-text">
    <%= link_to "Lets cook some #{@plant.name}!", recipes_path(plant: @plant.name) %>
  </p>
</div>