config/routes.rb
Rails.application.routes.draw do
  root to: 'plants#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post '/mygarden', to: "gardens#create", as: :gardens
  get '/mygarden', to: "gardens#show", as: :garden
  delete '/mygarden', to: "gardens#destroy", as: :garden_plants

  resources :plants, only: [:index, :show, :create]
  resources :recipes, only: [:index, :show]

  get '/developers', to: "api_keys#show", as: :developer
  post '/developers', to: "api_keys#create", as: :developers


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
        get '/plants/find', to: "plants#find_by"
      resources :plants, only: [:index, :show, :create, :update]
      resources :recipes, only: [:index]
      resources :frost_dates, only: [:index]
    end
  end
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  belongs_to :user, optional: true
  before_create :generate_access_token

  private
    def generate_access_token
      begin
        self.api_key = SecureRandom.hex
      end while self.class.exists?(api_key: api_key)
    end
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def create
    api_key = ApiKey.create
    if current_user.api_keys.empty?
      current_user.api_keys << api_key
      render :show
    else
      flash.now[:alert] = "Sorry #{current_user.name}, only one key per dev."
      render :show
    end
  end
end

app/views/api_keys/show.html.erb
<div class="container plant">
  <%= button_to "get api key", developers_path,  class: "btn btn-success button-dev" %>
  <div class="row">
    <% if !current_user.api_keys.empty? %>
      <h2 class="plant-text">your api key:</h2>
      <h3 class="plant-text"> <%= current_user.api_keys.first.api_key %> </h3>
      <h4 class="plant-text">send your api key through the params like so:</h4>
      <h5 class="plant-text">
        http://harvesthelper.herokuapp.com/api/v1/plants?api_key=YourApiKey
      </h5>
      <h5 class="plant-text">
        Other endpoints are:
        <ul style="bullets"><br>
          <p>get to:   http://harvesthelper.herokuapp.com/api/v1/plants/:plant_id?api_key=YourApiKey</p>
          <p>post to:   http://harvesthelper.herokuapp.com/api/v1/plants?api_key=YourApiKey</p>
          <p>put/patch to: http://harvesthelper.herokuapp.com/api/v1/plants/:plant_id?api_key=YourApiKey</p>
        </ul>
      </h5><br><br>
      <p class="plant-text">
        ***please don't be a dick and give your key to other people.  Let them sign in and get their own.  I mean I guess if they don't have facebook and can't login than it's okay to give them yours... but that's the only acceptable situation.***
      </p>
    <% end %>
  </div>
</div>