config/routes.rb
Rails.application.routes.draw do
  root to: 'plants#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post '/mygarden', to: "gardens#create", as: :gardens
  get '/mygarden', to: "gardens#show", as: :garden
  delete '/mygarden', to: "gardens#destroy", as: :garden_plants

  resources :plants, only: [:index, :show, :create]
  resources :recipes, only: [:index, :show]

  get '/developers', to: "api_keys#show", as: :developer
  post '/developers', to: "api_keys#create", as: :developers


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
        get '/plants/find', to: "plants#find_by"
      resources :plants, only: [:index, :show, :create, :update]
      resources :recipes, only: [:index]
      resources :frost_dates, only: [:index]
    end
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @plants = current_user.plants.order(name: :asc)
  end

  def create
    plant = Plant.find(params[:plant_id])
    if !current_user.plants.include?(plant)
      current_user.plants << plant
      flash[:info] = "#{plant.name} added to #{ActionController::Base.helpers.link_to 'garden', garden_path}!"
      redirect_to plant_path(plant)
    else
      flash[:alert] = "heyyy that's already in your #{ActionController::Base.helpers.link_to 'garden', garden_path}!"
      redirect_to plant_path(plant)
    end
  end

  def destroy
    plant = current_user.plants.find(params[:plant_id])
    current_user.plants.delete(params[:plant_id])
    flash[:alert] = "#{ActionController::Base.helpers.link_to plant.name, plant_path(plant)} removed from garden."
    redirect_to gardens_path
  end
end

app/views/gardens/show.html.erb
<div class="container-fluid plant">
  <h3 class="plant-text">
    <%= current_user.name %>'s garden
  </h3>
  <% if !current_user.plants.empty? %>
    <table class="table">
      <% @plants.each do |plant| %>
      <tr>
        <td>
          <%= link_to cl_image_tag(plant.image_url, :class=>'plant-image', :height=>100, :fetch_format=>:auto, :crop=>"scale"), plant_path(plant) %>
        </td>
        <td>
          <h4 class="plant-text"><%= link_to plant.name, plant_path(plant) %></h4>
          <div class="row">
            <div style="padding-left: 25px;">
              <%= link_to "recipes", recipes_path(plant: plant.name), class:"btn btn-warning btn-xs" %>
              <%= link_to "remove from garden", garden_plants_path(plant_id: plant.id), method: :delete, class:"btn btn-danger btn-xs" %>
            </div>
          </div>
         </td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <h4 class="plant-text">Your garden is empty.</h4>
    <h4 class="plant-text">Find some plants to add <%= link_to "here", plants_path %>.</h4>
  <% end %>
</div>